### ISSUE TITLE
New-PartnerAccessToken does not return a refreshtoken

### ISSUE THREAD

**Issue by gavsto** [microsoft/Partner-Center-PowerShell#190] opened 2019-11-15 01:17 UTC
# Steps to reproduce

> $ExchangeToken = New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716'  -Scopes 'https://outlook.office365.com/.default' -Tenant "MYPARTNERTENANTID" -UseDeviceAuthentication
> Utilising version 2.0.1911.3 of the PartnerCenter Powershell Module

## Expected behavior

> Object returned that contains RefreshToken, AccessToken, etc after going through the device code flow in a web browser successfully

## Actual behavior

> Object is returned with all expected information including an AccessToken, an expiry date etc but the RefreshToken is empty. This does not output an error when run

## Environment

PSVersion:  5.1.18362.145

**Comment by gavsto** [comment] 2019-11-15 01:28
So - this must have been a transient issue as it's now returning the token. I have no idea why it was not previously.

**Comment by gavsto** [comment] 2019-11-19 14:01
I am re-opening this because I have confirmed it has happening for more than one partner and on different devices. This is only working intermittently.

**Comment by isaiahwilliams** [comment] 2019-11-19 14:31
@gavsto can you provide an example of how you are calling this command?

**Comment by obeliskstreet** [comment] 2019-11-19 14:38
Same thing for me, I'd say at least 90% of the time it doesn't work.
I'm calling command from a standard powershell Window

**Comment by isaiahwilliams** [comment] 2019-11-19 15:18
@obeliskstreet can you give an example of how you are calling this command? What I am trying to determine is there an issue with a specific combination of parameters or not because I have not been able to reproduce this issue yet.

**Comment by obeliskstreet** [comment] 2019-11-19 15:26
From a powershell window, running the below. I've ran it tens of times today while I was troubleshooting another issue and I've managed to get a refresh token once.

New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716' -Scopes 'https://outlook.office365.com/.default' -Tenant 'xxxxxxxxxxxxxxxxxxxxxxxxx' -UseDeviceAuthentication

**Comment by isaiahwilliams** [comment] 2019-11-19 15:39
@obeliskstreet can you run the following and share the output from an execution were the refresh token value is missing? 

```powershell
New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716' -Scopes 'https://outlook.office365.com/.default' -Tenant 'xxxxxxxxxxxxxxxxxxxxxxxxx' -UseDeviceAuthentication -Debug
```

**Comment by obeliskstreet** [comment] 2019-11-19 16:00
I've hopefully removed all the unique bits from this, copy paste otherwise.

`PS C:\SecureAppModel> New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716' -Scopes 'https://outlook.office365.com/.default' -Tenant 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx' -UseDeviceAuthentication
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxxxxxxxx to authenticate.


RefreshToken            :
AccessToken             : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (this was a correct access token)
IsExtendedLifeTimeToken : False
UniqueId                : xxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxxx
ExpiresOn               : 19/11/2019 16:56:26 +00:00
ExtendedExpiresOn       : 19/11/2019 16:56:26 +00:00
TenantId                : xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxxxxxxxxxxxxxxxxx
Account                 : Account username: xxxxxxxxxxxx@xxxxxxxxx.onmicrosoft.com environment login.windows.net home
                          account id: AccountId:
                          xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxx
IdToken                 : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (this was a correct idtoken)
Scopes                  : {https://outlook.office365.com/.default,
                          https://outlook.office365.com/adminapi.accessasuser.all,
                          https://outlook.office365.com/ffopowershell.accessasuser.all,
                          https://outlook.office365.com/remotepowershell.accessasuser.all}
User                    :`

**Comment by isaiahwilliams** [comment] 2019-11-19 21:00
@obeliskstreet thank you for sharing that information. Can you run the command again with the `-Debug` parameter? It would be helpful to see what is happening and the debug output will provide some insight into whether or not the token is being cached.

**Comment by obeliskstreet** [comment] 2019-11-22 11:47
Sorry for delay in coming back to this. I've tried a couple of times with debug this morning and am given the refresh token, not sure if something changed.

I do have some errors though which may be of use.

``DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:07 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438]
=== Request Data ===
Authority Provided? - True
Scopes - https://outlook.office365.com/.default
Extra Query Params Keys (space separated) -
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:07 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] === Token Acquisition (DeviceCodeRequest) started:
 Cache Provided: True
 Authority Host: login.microsoftonline.com
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:07 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Resolving authority endpoints... Already resolved? - TRUE
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:08 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Response status code does not indicate success: 400 (BadRequest).
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:08 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] HttpStatusCode: 400: BadRequest
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:08 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: authorization_pending
HTTP StatusCode 400
CorrelationId 72d13318-c2c4-4fc6-b62a-fc0e953e1438
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:13 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Response status code does not indicate success: 400 (BadRequest).
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:13 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] HttpStatusCode: 400: BadRequest
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:13 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: authorization_pending
HTTP StatusCode 400
CorrelationId 72d13318-c2c4-4fc6-b62a-fc0e953e1438
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:18 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Response status code does not indicate success: 400 (BadRequest).
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:18 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] HttpStatusCode: 400: BadRequest
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:18 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: authorization_pending
HTTP StatusCode 400
CorrelationId 72d13318-c2c4-4fc6-b62a-fc0e953e1438
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:24 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Response status code does not indicate success: 400 (BadRequest).
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:24 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] HttpStatusCode: 400: BadRequest
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:24 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: authorization_pending
HTTP StatusCode 400
CorrelationId 72d13318-c2c4-4fc6-b62a-fc0e953e1438
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:29 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Checking client info returned from the server..
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:29 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Saving Token Response to cache..
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:29 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Looking for scopes for the authority in the cache which intersect with
https://outlook.office365.com/.default
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:29 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Intersecting scope entries count - 2
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:29 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Matching entries after filtering by user - 1
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:29 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] Saving RT in cache...
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:29] Serializing token cache with 1
items.
DEBUG: MSAL Info False (False) MSAL 3.0.8.0 MSAL.CoreCLR N/A [11/22/2019 11:44:29 -
72d13318-c2c4-4fc6-b62a-fc0e953e1438] === Token Acquisition finished successfully. An access token was returned with
Expiration Time: 11/22/2019 12:44:29 +00:00 ===

**Comment by isaiahwilliams** [comment] 2019-11-24 02:10
The error above are excepted because the module is using MSAL and it will check periodically if device authentication has been completed. Usually if the refresh token is not included in the output that means there was something wrong with the cache. Over the past few releases there have been a number of minor changes to authentication. I would recommend that you update to the latest version, and if there is an issue with the cache the error should be thrown now. Previously it was being handled and with the latest release that behavior has changed.

Let's leave this open for the next few days. If @gavsto and @obeliskstreet do not have any issues with the latest release we will close this issue.

**Comment by isaiahwilliams** [comment] 2019-11-29 19:26
If this issue is still happening please feel free to re-open this issue. Also, I wanted to share that work on the next release has started and it contains additionally changes to this process to ensure everything is returned consistently

**Closed by isaiahwilliams** 2019-11-29 19:26 UTC
