### ISSUE TITLE
New-PartnerAccessToken returns error AADSTS50011 when -UseAuthorizationCode is used

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#158] opened 2019-09-16 12:49 UTC
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

When using the below command with application that was created from the guidance on v1.5 module we get the error below in the browser after authentication.

```powershell
$t=New-PartnerAccessToken -ApplicationId '<app id>' -Credential (Get-Credential) -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Tenant '<tenant id>' -UseAuthorizationCode
```

```
AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application:
```

Seems the problem is that this new v2. module requires that the application has https://localhost as reply url in the app where in previous version the guidance was that the app should be created with urn:ietf:wg:oauth:2.0:oob reply url. The module should allow for both or does not require the reply url value at all.

## Expected behavior

> Share the expected output

Authtenticate

## Actual behavior

> What is the behavior observed?

AAD error.

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

PS 5.1 and PS 6.2.3

**Comment by cblackuk** [comment] 2019-09-17 07:22
![image](https://user-images.githubusercontent.com/28607803/65020074-50d99e80-d924-11e9-8f9a-2d9c8208a605.png)

**Comment by cblackuk** [comment] 2019-09-17 07:35
The code that was merged but not yet published "might" fix the refresh token but it will not fix this issue IMHO, but I guess we will have to test it.

@slavizh @isaiahwilliams

**Comment by slavizh** [comment] 2019-09-18 07:57
@isaiahwilliams by the look of the merge request seems we will have to update our apps rather the code being changed, correct?

**Comment by cblackuk** [comment] 2019-09-18 08:41
That is how I have read it - seems wrong to me...

**Comment by slavizh** [comment] 2019-09-18 08:50
Yes. Especially that it was not documented that is breaking change.

**Comment by slavizh** [comment] 2019-09-20 12:15
@isaiahwilliams Several days have passed and the only update was merged that didn't fixed the issue. Is the issue is investigated? Do we need to provide more information? When we can expect a fix?

**Comment by cblackuk** [comment] 2019-09-20 12:18
Agreed with @slavizh we need some sort of resolution as this is a major showstopper for us CSPs... we need to get some traction on this from MSFT, please...

**Comment by slavizh** [comment] 2019-09-21 06:56
@isaiahwilliams This issue is still present with the latest  version (.5) let us know if will the new guidance will be to include https://localhost in reply URLs of the AAD app? Also if that is the case should we remove urn:ietf:wg:oauth:2.0:oob or it should stay?

**Comment by slavizh** [comment] 2019-09-21 06:57
In any case you should allow interrupting the process with ctrl +c and having some default timeout if authentication is not done. I think that is present in Az module if I remember correctly.

**Comment by cblackuk** [comment] 2019-09-23 04:49
So when can we expect this to be resolved please? @isaiahwilliams

**Comment by cblackuk** [comment] 2019-09-23 06:16
@slavizh can we just add localhost and leave urn:ietf:wg:oauth:2.0:oob and it still works? Have you tested that by any chance?

**Comment by slavizh** [comment] 2019-09-23 06:43
@cblackuk yes works if both are added.

**Comment by cblackuk** [comment] 2019-09-23 06:52
Thanks @slavizh I guess I will just add it for now...

**Comment by isaiahwilliams** [comment] 2019-09-25 04:31
@cblackuk  and @slavizh this is the expected behavior with the 2.0 release. Thank you for pointing out this breaking change is not included in the breaking changes documentation. I will work on getting that fixed shortly. The reason for this change is that PowerShell Core does not support the Windows form approach that was used in the past. To ensure that the `New-PartnerAccessToken` command could function identically between PowerShell 5.1 and PowerShell Core this change was required. You can learn about the expected configurations [here](https://docs.microsoft.com/powershell/module/partnercenter/new-partneraccesstoken). 

Please let us know if you have any questions.

**Closed by isaiahwilliams** 2019-09-25 04:31 UTC

**Comment by dkattan** [comment] 2020-01-02 18:35
For anyone still struggling with this, the solution for me was to manipulate the app registration with the following:
```
"replyUrlsWithType": [
		{
			"url": "urn:ietf:wg:oauth:2.0:oob",
			"type": "Web"
		},
        {
            "url": "http://localhost:8400",
            "type": "Web"
        }
	],
```
