### ISSUE TITLE
Get-PartnerCustomerOrder -CustomerID $ID

### ISSUE THREAD

**Issue by qbihay** [Microsoft/Partner-Center-PowerShell#13] opened 2018-09-13 06:32 UTC
Hello,

# Steps to reproduce

> What steps can reproduce the defect?
$CustomerID = Get-PartnerCustomer | select -first 1
Get-PartnerCustomerOrder -CustomerId $CustomerID.CustomerId

## Actual Error

> What is the error observed?
Get-PartnerCustomerOrder : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-PartnerCustomerOrder -CustomerId $CustomerID.CustomerId
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomerOrder], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerOrder

## Diagnostic logs
$ERROR[0] | fl -force

Exception             : System.NullReferenceException: Object reference not set to an instance of an object.
                           at Microsoft.Store.PartnerCenter.PowerShell.Models.Orders.PSOrder.CloneAdditionalOperations(Order order) in D:\a\1\s\src\PowerShell\Models\Orders\PSOrder.cs:line
                        79
                           at Microsoft.Store.PartnerCenter.PowerShell.Common.ResourceExtensions.CopyFrom[TInput,TOutput](TOutput value, TInput other, Action`1 operation) in
                        D:\a\1\s\src\PowerShell\Common\ResourceExtensions.cs:line 43
                           at Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerOrder.<>c.<GetCustomerOrders>b__14_0(Order o) in
                        D:\a\1\s\src\PowerShell\Commands\GetPartnerCustomerOrder.cs:line 119
                           at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
                           at System.Management.Automation.MshCommandRuntime._WriteObjectsSkipAllowCheck(Object sendToPipeline)
                           at System.Security.SecurityContext.Run(SecurityContext securityContext, ContextCallback callback, Object state)
                           at System.Management.Automation.MshCommandRuntime.WriteObject(Object sendToPipeline, Boolean enumerateCollection)
                           at System.Management.Automation.Cmdlet.WriteObject(Object sendToPipeline, Boolean enumerateCollection)
                           at Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerOrder.GetCustomerOrders(String customerId, Nullable`1 billingCycle) in
                        D:\a\1\s\src\PowerShell\Commands\GetPartnerCustomerOrder.cs:line 119
                           at Microsoft.Store.PartnerCenter.PowerShell.Commands.PartnerPSCmdlet.ProcessRecord() in D:\a\1\s\src\PowerShell\Commands\PartnerPSCmdlet.cs:line 61
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomerOrder], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerOrder
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :

**Comment by isaiahwilliams** [comment] 2018-09-13 15:14
Hi @qbihay, 

I have identified the root cause of this issue and corrected it. I am planning to release an updated version of the module by the end of the week. If you discover any additional issues please open a new issue and I will be sure to get them corrected as soon as possible. 

Thank you for bring this issue to my attention.

**Comment by isaiahwilliams** [comment] 2018-09-14 03:37
Hi @qbihay, 

I have merged PR #15 which addressed this issue. I will be publishing an updated version of the module shortly. Please let me know if you have discovered any other issue.

**Closed by isaiahwilliams** 2018-09-14 03:37 UTC
Labels: bug

**Comment by qbihay** [comment] 2018-09-17 07:37
Hello,

I've updated to module and now it work. 
Thanks !
