### ISSUE TITLE
Set-PartnerCustomerUserLicense License Removal Inconsistent with Addition

### ISSUE THREAD

**Issue by azmrb** [microsoft/Partner-Center-PowerShell#129] opened 2019-05-17 01:24 UTC
# Steps to reproduce
$license = New-Object -TypeName Microsoft.Store.PartnerCenter.PowerShell.Models.Licenses.PSLicenseAssignment
$licenses = New-Object -TypeName Microsoft.Store.PartnerCenter.PowerShell.Models.Licenses.PSLicenseUpdate
$licenses.LicensesToRemove.Add($license)

Based on documentation in help and LicenseUpdate Class of Microsoft.Store.PartnerCenter.Models.Licenses Namespace

## Expected behavior
$licenses.LicensesToRemove.Add($license) updates the $licenses object correctly.
> Share the expected output
$licenses

LicensesToAssign                       LicensesToRemove
----------------                       ----------------
{f1b66f95-1aca-4e0d-9d02-0c9ab2959762} {4a1626c7-bebd-4c98-a2df-08d685c4815f}

## Actual behavior
$licenses.LicensesToRemove.Add($license) Returns false.
whereas
$licenses.LicensesToRemove.Add('4a1626c7-bebd-4c98-a2df-08d685c4815f') updates the $licenses object correctly.

## Environment

Win 10 Ent PWSH 6.2 
1.5.1904.3 PartnerCenter.NetCore
GUIDs changed for included examples.

**Comment by isaiahwilliams** [comment] 2019-12-22 00:28
The reason for this design is the expected values with the Partner Center API. Since this is working as designed I am going to close this issue. As we start to plan future updates to the module one of the areas where we plan to focus is the license management functionality. Thank you for sharing this feedback it has helped me realize one of the areas that needs to be re-thought is license management.

**Closed** 2019-12-22 00:28 UTC
