### ISSUE TITLE
Get-PartnerCustomerRelationship -> results in 1002 Authorization Failed

### ISSUE THREAD

**Issue by itsChris** [Microsoft/Partner-Center-PowerShell#49] opened 2018-12-12 09:14 UTC
# Steps to reproduce

PS C:\> Import-Module PartnerCenter
PS C:\> Connect-PartnerCenter -ApplicationId '86185200-3e87-48b4-8d00-xxxxxxxxxxxx'

Account       : Microsoft.Store.PartnerCenter.PowerShell.Profile.AzureAccount
ApplicationId : 86185200-3e87-48b4-8d00-xxxxxxxxxxxx
CountryCode   : CH
Environment   : GlobalCloud
Locale        : de-CH

PS C:\> Get-PartnerCustomer

CustomerId                           Domain                          Name
----------                           ------                          ----
xxxxxxxx-2b8c-4e04-99ee-30d42aa1745b removed.ch                     Removed
xxxxxxxx-84b5-44e8-b473-dbb786b234ff removed.com           			Removed
xxxxxxxx-0e01-4507-b1ca-2e86d798478c removed.com 					Removed
xxxxxxxx-b1e2-4c07-aa2c-c5e398425b9c removed.ch                 	Removed
xxxxxxxx-8c77-470b-a4bf-0be6a84b033d removed.com         			Removed

PS C:\> Get-PartnerCustomerRelationship -CustomerId 'xxxxxxxx-84b5-44e8-b473-dbb786b234ff'
Get-PartnerCustomerRelationship : 1002 Authorization Failed
At line:1 char:1
+ Get-PartnerCustomerRelationship -CustomerId 'xxxxxxxx-84b5-44e8-b473- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomerRelationship], PartnerPSException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Exceptions.PartnerPSException,Microsoft.Store.P
   artnerCenter.PowerShell.Commands.GetPartnerCustomerRelationship

> What steps can reproduce the defect?
see above

## Expected behavior

> Share the expected output

-> it should list the PartnerCustomerRelationship i believe

**Comment by isaiahwilliams** [comment] 2019-01-01 23:54
Hi @itsChris, 

This is an indication that the relationship between yourself and the customer has been broken. Are you able to access the customer in question through Partner Center without any error?

**Comment by cblackuk** [comment] 2019-01-02 10:37
This one however is not related to any broken sub. It does not matter which one you are querying, or who you are logged in as (SPN or Admin) it is just broken full stop.  @isaiahwilliams

**Comment by itsChris** [comment] 2019-01-04 09:13
@isaiahwilliams Well, it might be an issue to list a relationship of a 'broken' customer. *but* if i call the method without the -customerid parameter, the error remains the same. with other words, if - in case - one customer relationship is broken, the listing of all the relationsships will fail with the mention 1002 error. Just checked again. 

cheers

Christian

**Comment by cblackuk** [comment] 2019-01-08 12:03
So we finally got rid of the broken customer with MS Support help but still getting 1002 on getting the reletionship on ALL customers ;-(

**Comment by stullith** [comment] 2019-01-21 14:19
I am seeing the same issue with all customers on my CSP tenant. I can view the all details of the customer tenant in the portal but I'm unable to fetch the relationship status with the Get-PartnerCustomerRelationship command.

**Comment by isaiahwilliams** [comment] 2019-01-22 19:33
@itsChris, @cblackuk, and @stullith this is an issue with the Partner Center API, so I have reached out to the engineering team responsible for this feature. They are actively investigating the issue and I am hopeful that there will be information we can share this week. Since each of you are experiencing this issue I would like to encourage you to open a support ticket stating the request to get a customer relationships is failing with the following error `{"code":1002,"description":"Authorization Failed","data":[],"source":"PartnerFD"}`.

Doing this will help the team working to resolve this issue to capture all of the information need to identify the root cause. Please let me know if you have any concerns or questions regarding the PowerShell module and I will be glad to help when and where I can.

**Comment by cblackuk** [comment] 2019-01-24 09:05
Thanks @isaiahwilliams I opened a support case as requested. Will keep you guys update on the progress.

**Comment by isaiahwilliams** [comment] 2019-01-27 16:21
Hi @itsChris, @cblackuk, and @stullith this command is going to be replaced in a future release. The underlying feature of the Partner Center API, that was being called is intended to retrieve a list of indirect resellers for the specified customer. If you are not an indirect provider and you try this operation, currently, the expceted outcome is the authorization failed error. I apologizes for the confusion regarding this and I wanted to share that we will be retiring this command to avoid any further confusion. Thank you for all your input and opening the support tickets.

**Closed by isaiahwilliams** 2019-01-27 16:21 UTC
Labels: Partner Center API, help wanted

**Comment by cblackuk** [comment] 2019-01-28 08:47
It was explained to me during my support request and troubleshooting, glad we finally got to the bottom of it. Thanks @isaiahwilliams for looking into it for us.
