### ISSUE TITLE
Get-PartnerAccessToken sometimes returns 2 tokens

### ISSUE THREAD

**Issue by penicaudm** [microsoft/Partner-Center-PowerShell#286] opened 2020-03-05 13:07 UTC
# Steps to reproduce
Generate a new partner access token using New-PartnerAccessToken
```Powershell
# Get an access token
$PartnerAccessTokenSplat = @{
    Scopes        = 'https://api.partnercenter.microsoft.com/user_impersonation'
    ApplicationID = $AppID
    TenantID      = $tenantID
    RefreshToken  = $refreshtoken
}
$token = New-PartnerAccessToken @PartnerAccessTokenSplat
```
## Expected behavior

Object returned should be [Microsoft.Store.PartnerCenter.PowerShell.Models.Authentication.AuthResult] with properties:

AccessToken
Account
CorrelationId
ExpiresOn
ExtendedExpiresOn
IdToken
IsExtendedLifeTimeToken
RefreshToken
Scopes
TenantId
UniqueId
User

## Actual behavior

Object returned is 2 different tokens, which creates an object of type System.Object[] instead containing 2 tokens. This result in auth failure using Connect-PartnerCenter because System.Object[] cannot be converted into System.String

## Diagnostic logs
PSVersiontable : PS 5.1

## Environment
Script is running on Microsoft Azure Automation Runbooks. As far as I know, I haven't been able to reproduce it on a desktop. This may be due to the Azure Automation backend, though I don't know.

## Side Note
This behavior isn't happening consistently.
A simple fix has been to add this simple piece of code.
```powershell
if ($token.Count -ne 1)
{
    $Token = $Token[0]
}
```

**Comment by isaiahwilliams** [comment] 2020-04-04 14:59
@penicaudm I have not been able to reproduce this particular issue. This particular command is design in such a way that only one access token will be returned. I would recommend that you update to the latest version, if you are not already and see if that resolves your issue. Since we are unable to currently reproduce the issue I am going to close this issue.

**Closed by isaiahwilliams** 2020-04-04 14:59 UTC
