### ISSUE TITLE
Get-PartnerCustomerBillingProfile : There were not enough free threads in the ThreadPool to complete the operation

### ISSUE THREAD

**Issue by adrianwells** [microsoft/Partner-Center-PowerShell#230] opened 2019-12-16 21:59 UTC
# Steps to reproduce

ForEach-Object loops through CustomerIDs issuing cmdlets like Get-PartnerCustomerBillingProfile

## Expected behavior

Expected output to be valid not reporting ThreadPool issue

## Actual behavior

Error message stating `Get-PartnerCustomerBillingProfile : There were not enough free threads in the ThreadPool to complete the operation`

## Environment

```
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1903
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

 $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145
```

**Comment by isaiahwilliams** [comment] 2019-12-17 01:00
@adrianwells thank you for sharing this information. I am looking to reproduce the issue, so it will be easier to verify that it has been resolved. Would you be able to share the following?

1. What version of the module are you running? 
2. How customers did it processes before encountering the error?
3. What type of processor does yoursystem have?
4. Are you running this on a VM in Azure? If so what size?

**Comment by adrianwells** [comment] 2019-12-17 16:48
@isaiahwilliams thank you for the reply. Here is the requested information:
1. Module Information version:
```

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.1      partnercenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Disconnect-PartnerCenter...}

```
2. Over 100
3. CPU info:
```
Caption           : Intel64 Family 6 Model 142 Stepping 9
DeviceID          : CPU0
Manufacturer      : GenuineIntel
MaxClockSpeed     : 2904
Name              : Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
SocketDesignation : U3E1
```
4. Not running in Azure, this was run on physical hardware

**Comment by isaiahwilliams** [comment] 2019-12-17 20:48
@adrianwells thank you for sharing this information. I have found a way to reproduce the issue, and through that I have actually discovered the root cause of the issue. Right now I am working to develop a plan on best to resolve this particular issue. I am hopefully that it will not take too long to get everything resolved, but with the holidays there might be a slight delay. 

If you have a process that needs to be completed now, then you can work around this issue by connecting using an access token.

```powershell
Connect-PartnerCenter -AccessToken $accessToken
```

**Comment by adrianwells** [comment] 2019-12-18 15:00
@isaiahwilliams Thank you for the update, effort to resolve, and the workaround suggestion (have yet to try it but good to know).

**Comment by isaiahwilliams** [comment] 2019-12-19 17:57
@adrianwells can you update to version [3.0.2](https://www.powershellgallery.com/packages/PartnerCenter/3.0.2) and try this operation again? 

The issue has been resolved, but before I close this I wanted to confirm with you that everything is working.

**Comment by isaiahwilliams** [comment] 2019-12-27 16:53
I have confirmed with another individual who was encountering this issue that it has been resolved. If you are still having issues please let us know.

**Closed by isaiahwilliams** 2019-12-27 16:53 UTC
Labels: bug
